### ISSUE TITLE
quality check crystallib 1.0

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#98] opened 2022-11-14 05:36 UTC
* check docu for all parts, every directory in crystal lib needs to work and be documented properly
* check tests

if issues consult with Kristof

**Comment by ashraffouda** [comment] 2024-02-04 12:32
duplicate of https://github.com/freeflowuniverse/crystallib/issues/100

**Closed as completed by ashraffouda** 2024-02-04 12:32 UTC
Labels: type_story
